// Generates the canonical OAF Alpha 0 app skeleton (issue #8).
// Uses only Node built-ins; no third-party dependencies.

import { loadStackSnapshot } from "./stack-snapshot.ts";
import { BLESSED_PACKAGE_MANAGER, BLESSED_PACKAGE_SCRIPTS } from "./command-policy.ts";

const STACK_SNAPSHOT = loadStackSnapshot();
const STACK = STACK_SNAPSHOT.id;
const DOCS_PACK = STACK_SNAPSHOT.docsPack;

function readme(name: string): string {
  return `# ${name}

This app was generated by **OAF** (Opinionated App Factory) — an all-in-one,
convention-locked coding agent and app factory.

## This is an Alpha 0 skeleton

This is **not** a full working Next.js app yet. It is a predictable OAF app
workspace following the canonical structure from docs/app-structure.md.

## Next step

Run the doctor check to verify the skeleton:

    oaf doctor

If oaf is not on your PATH in local development, run it directly from the
OAF repo:

    node <oaf-repo>/bin/oaf.ts doctor

## Notes

- Stack snapshot: OAF Stack 0.1 (see oaf/stack.json).
- Docs pack: stack-0.1 (see oaf/docs-pack.json).
- No dependencies are installed yet. The pnpm-lock.yaml lockfile is not
  generated by this skeleton. It will be created on the first real
  pnpm install once dependencies are added (see issues #6 and #14).
- Do not copy the full docs pack into this app; the OAF repo owns docs packs.
`;
}

function doctorMjs(): string {
  return [
    "#!/usr/bin/env node",
    'import { existsSync } from "node:fs";',
    'import { join } from "node:path";',
    "",
    "const REQUIRED_FILES = [",
    '  "oaf/app.json",',
    '  "oaf/stack.json",',
    '  "oaf/docs-pack.json",',
    '  "README.md",',
    '  "package.json",',
    "];",
    "const REQUIRED_DIRS = [",
    '  "app", "components", "features", "lib", "server",',
    '  "db", "tests", "e2e", "public", "docs", "oaf",',
    "];",
    "",
    "const dir = process.cwd();",
    "let failed = 0;",
    "for (const f of REQUIRED_FILES) {",
    "  const ok = existsSync(join(dir, f));",
    '  console.log((ok ? "PASS" : "FAIL") + "  " + f);',
    "  if (!ok) failed++;",
    "}",
    "for (const d of REQUIRED_DIRS) {",
    "  const ok = existsSync(join(dir, d));",
    '  console.log((ok ? "PASS" : "FAIL") + "  " + d + "/");',
    "  if (!ok) failed++;",
    "}",
    "if (failed > 0) {",
    '  console.error("\\n" + failed + " check(s) failed. This is not a valid OAF app.");',
    "  process.exit(1);",
    "}",
    'console.log("\\nDoctor: this is a valid OAF Alpha 0 app skeleton.");',
  ].join("\n");
}

function sanityTest(): string {
  return [
    'import { existsSync } from "node:fs";',
    'import { join } from "node:path";',
    "",
    "const checks = [",
    '  ["oaf/app.json", "oaf/app.json"],',
    '  ["oaf/stack.json", "oaf/stack.json"],',
    '  ["oaf/docs-pack.json", "oaf/docs-pack.json"],',
    '  ["README.md", "README.md"],',
    '  ["package.json", "package.json"],',
    '  ["app", "app"],',
    '  ["components", "components"],',
    '  ["features", "features"],',
    '  ["lib", "lib"],',
    '  ["server", "server"],',
    '  ["db", "db"],',
    '  ["tests", "tests"],',
    '  ["e2e", "e2e"],',
    '  ["public", "public"],',
    '  ["docs", "docs"],',
    "];",
    "",
    "let failed = 0;",
    "for (const [label, rel] of checks) {",
    "  const ok = existsSync(rel);",
    '  console.log((ok ? "PASS" : "FAIL") + "  " + label);',
    "  if (!ok) failed++;",
    "}",
    "if (failed > 0) {",
    '  console.error("\\n" + failed + " check(s) failed.");',
    "  process.exit(1);",
    "}",
    'console.log("\\nAll sanity checks passed.");',
  ].join("\n");
}

export function getAppTemplates(name: string, createdAt: string) {
  const packageJson = JSON.stringify(
    {
      name,
      private: true,
       packageManager: BLESSED_PACKAGE_MANAGER,
       scripts: BLESSED_PACKAGE_SCRIPTS,
    },
    null,
    2,
  )!;

  const appJson = JSON.stringify(
    { name, createdBy: "oaf", createdAt },
    null,
    2,
  )!;
  const stackJson = JSON.stringify({ oafStack: STACK }, null, 2)!;
  const docsPackJson = JSON.stringify(
    { docsPack: DOCS_PACK, oafStack: STACK },
    null,
    2,
  )!;

  return {
    "README.md": readme(name),
    "package.json": packageJson,
    "oaf/app.json": appJson,
    "oaf/stack.json": stackJson,
    "oaf/docs-pack.json": docsPackJson,
    "oaf/doctor.mjs": doctorMjs(),
    "oaf/receipts/.gitkeep": "",
    "tests/sanity.test.mjs": sanityTest(),
    "tests/unit/.gitkeep": "",
    "tests/integration/.gitkeep": "",
    "e2e/.gitkeep": "",
    "public/.gitkeep": "",

    "app/layout.tsx": `export const metadata = { title: "OAF App" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    "app/page.tsx": `export default function HomePage() {
  return (
    <main>
      <h1>OAF App</h1>
    </main>
  );
}
`,
    "app/api/.gitkeep": "",

    "components/ui/.gitkeep": "",
    "components/shared/.gitkeep": "",

    "features/example-feature/components/.gitkeep": "",
    "features/example-feature/server/.gitkeep": "",
    "features/example-feature/schemas.ts": `// Example feature schema placeholder.
// Replace with real Drizzle schemas as the app grows.
export const exampleSchema = {
  id: "string",
} as const;
`,
    "features/example-feature/types.ts": `// Example feature types placeholder.
export type ExampleItem = {
  id: string;
};
`,
    "features/example-feature/index.ts": `// Public surface for the example feature.
export * from "./types";
`,

    "lib/env.ts": `// Environment parsing placeholder.
// Use a validated accessor here; do not read secrets casually.
export function getEnv(key: string, fallback?: string): string | undefined {
  return process.env[key] ?? fallback;
}
`,
    "lib/result.ts": `// Minimal Result type for boundary-safe returns.
export type Result<T, E = Error> =
  | { ok: true; value: T }
  | { ok: false; error: E };

export function ok<T>(value: T): Result<T> {
  return { ok: true, value };
}

export function err<E>(error: E): Result<never, E> {
  return { ok: false, error };
}
`,
    "lib/utils.ts": `// Small shared utilities. Keep this minimal; not a business-logic dump.
export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
`,

    "server/auth/.gitkeep": "",
    "server/actions/.gitkeep": "",

    "db/schema/.gitkeep": "",
    "db/migrations/.gitkeep": "",
    "db/seed/.gitkeep": "",
    "db/client.ts": `// Database client placeholder.
//
// During real implementation wire up Drizzle + Postgres here, using the
// pinned versions from the OAF Stack 0.1 snapshot.
export const db = {
  // placeholder
};
`,

    "docs/app.md": `# App documentation

This is a placeholder for app-specific human documentation. It is generated
into every OAF app and is separate from OAF's own repository docs.

Replace it with real docs as the app grows.
`,

    "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "preserve",
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "allowJs": true,
    "noEmit": true
  },
  "include": ["app", "components", "features", "lib", "server", "db", "tests"]
}
`,
    "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`,
    "postcss.config.mjs": `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`,
    "docker-compose.yml": `services:
  postgres:
    image: ${STACK_SNAPSHOT.data.postgresImage}
    environment:
      POSTGRES_USER: oaf
      POSTGRES_PASSWORD: oaf
      POSTGRES_DB: oaf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
`,
    "Dockerfile": `# OAF Alpha 0 placeholder Dockerfile.
#
# Real Docker/Coolify build behavior is intentionally deferred until the
# generated app has a real dependency install and lockfile.
#
# Do not add package installation here without following:
# - docs/sandbox.md
# - docs/dependencies.md
# - docs/package-policy.md
`,
  };
}

export type AppTemplateTree = ReturnType<typeof getAppTemplates>;
export type AppTemplatePath = keyof AppTemplateTree;
